import {
  MessageSquare,
  GraduationCap,
  HelpCircle,
  FileText,
  PenLine,
  BookOpen,
  UserCircle2,
  Hash,
  Languages,
  MessageCircle,
  ImageIcon,
  Video,
  Mic,
  StickyNote,
  Flame,
  Youtube,
  Clapperboard,
  Lightbulb,
  Image as ImageLucide,
  Film,
  Sparkles,
  ScrollText,
  type LucideIcon,
} from "lucide-react";

export type ToolCategory = "chat" | "study" | "writing" | "social" | "creator" | "media";

export type Tool = {
  id: string;
  name: { en: string; hi: string };
  tagline: { en: string; hi: string };
  category: ToolCategory;
  icon: LucideIcon;
  accent: "primary" | "accent" | "pink" | "amber" | "violet";
  kind: "chat" | "single" | "placeholder";
  inputLabel?: { en: string; hi: string };
  inputPlaceholder?: { en: string; hi: string };
  badge?: { en: string; hi: string };
};

export const TOOL_CATEGORIES: { id: "all" | ToolCategory; en: string; hi: string }[] = [
  { id: "all", en: "All", hi: "सभी" },
  { id: "chat", en: "Chat", hi: "बातचीत" },
  { id: "study", en: "Study", hi: "अध्ययन" },
  { id: "writing", en: "Writing", hi: "लेखन" },
  { id: "social", en: "Social", hi: "सोशल" },
  { id: "creator", en: "Creator", hi: "क्रिएटर" },
  { id: "media", en: "Media", hi: "मीडिया" },
];

export const TOOLS: Tool[] = [
  {
    id: "chat",
    name: { en: "AI Chat Assistant", hi: "AI चैट सहायक" },
    tagline: { en: "Conversational AI with memory.", hi: "याद रखने वाला AI साथी।" },
    category: "chat",
    icon: MessageSquare,
    accent: "primary",
    kind: "chat",
    badge: { en: "Popular", hi: "लोकप्रिय" },
  },
  {
    id: "homework",
    name: { en: "Homework Solver", hi: "होमवर्क हल" },
    tagline: { en: "Step-by-step answers for any subject.", hi: "हर विषय के लिए चरण-दर-चरण उत्तर।" },
    category: "study",
    icon: GraduationCap,
    accent: "accent",
    kind: "single",
    inputLabel: { en: "Paste your question", hi: "अपना सवाल लिखें" },
    inputPlaceholder: {
      en: "e.g. Solve: 2x + 5 = 13, then explain.",
      hi: "उदा. हल करें: 2x + 5 = 13, और समझाएँ।",
    },
  },
  {
    id: "qa",
    name: { en: "Question & Answer AI", hi: "प्रश्न-उत्तर AI" },
    tagline: { en: "Accurate answers from world knowledge.", hi: "विश्व ज्ञान से सटीक उत्तर।" },
    category: "study",
    icon: HelpCircle,
    accent: "violet",
    kind: "single",
    inputPlaceholder: { en: "Ask anything…", hi: "कुछ भी पूछें…" },
  },
  {
    id: "notes",
    name: { en: "Notes Generator", hi: "नोट्स जनरेटर" },
    tagline: { en: "Clean revision notes for any topic.", hi: "किसी भी विषय के सुथरे नोट्स।" },
    category: "study",
    icon: StickyNote,
    accent: "amber",
    kind: "single",
    inputPlaceholder: { en: "Topic, syllabus, chapter…", hi: "विषय, अध्याय…" },
  },
  {
    id: "resume",
    name: { en: "Resume Generator", hi: "रिज़्यूम जनरेटर" },
    tagline: { en: "ATS-friendly resumes in seconds.", hi: "ATS के लिए तैयार रिज़्यूम।" },
    category: "writing",
    icon: FileText,
    accent: "accent",
    kind: "single",
    inputLabel: { en: "Tell us about yourself", hi: "अपने बारे में बताएँ" },
    inputPlaceholder: {
      en: "Name, role, years of experience, key skills, recent projects…",
      hi: "नाम, भूमिका, अनुभव, कौशल, हाल के प्रोजेक्ट…",
    },
  },
  {
    id: "essay",
    name: { en: "Essay Writer", hi: "निबंध लेखक" },
    tagline: { en: "Long-form essays with structure.", hi: "सुव्यवस्थित निबंध।" },
    category: "writing",
    icon: PenLine,
    accent: "pink",
    kind: "single",
    inputPlaceholder: { en: "Essay topic…", hi: "निबंध का विषय…" },
  },
  {
    id: "story",
    name: { en: "Story Generator", hi: "कहानी जनरेटर" },
    tagline: { en: "Imaginative short stories.", hi: "रचनात्मक लघु कथाएँ।" },
    category: "writing",
    icon: BookOpen,
    accent: "violet",
    kind: "single",
    inputPlaceholder: { en: "Story premise…", hi: "कहानी का आरंभ…" },
  },
  {
    id: "script",
    name: { en: "Script Generator", hi: "स्क्रिप्ट जनरेटर" },
    tagline: { en: "Video, ad, podcast & skit scripts.", hi: "वीडियो, ऐड, पॉडकास्ट स्क्रिप्ट।" },
    category: "writing",
    icon: ScrollText,
    accent: "primary",
    kind: "single",
    inputPlaceholder: { en: "What is the script for?", hi: "स्क्रिप्ट किस लिए?" },
  },
  {
    id: "bio",
    name: { en: "Bio Generator", hi: "बायो जनरेटर" },
    tagline: { en: "Crisp social profile bios.", hi: "शानदार सोशल बायो।" },
    category: "social",
    icon: UserCircle2,
    accent: "amber",
    kind: "single",
    inputPlaceholder: { en: "About me / niche…", hi: "मेरे बारे में…" },
  },
  {
    id: "caption",
    name: { en: "Caption Generator", hi: "कैप्शन जनरेटर" },
    tagline: { en: "Captions for Instagram & Facebook.", hi: "इंस्टा/फेसबुक कैप्शन।" },
    category: "social",
    icon: Hash,
    accent: "pink",
    kind: "single",
    inputPlaceholder: { en: "Describe your post…", hi: "अपनी पोस्ट बताएँ…" },
  },
  {
    id: "hashtag",
    name: { en: "Hashtag Generator", hi: "हैशटैग जनरेटर" },
    tagline: { en: "Trending hashtag packs.", hi: "ट्रेंडिंग हैशटैग।" },
    category: "social",
    icon: Hash,
    accent: "accent",
    kind: "single",
    inputPlaceholder: { en: "Post topic / niche…", hi: "पोस्ट का विषय…" },
  },
  {
    id: "hook",
    name: { en: "Viral Hook Generator", hi: "वायरल हुक जनरेटर" },
    tagline: { en: "Scroll-stopping first lines.", hi: "स्क्रॉल रोकने वाली शुरुआत।" },
    category: "creator",
    icon: Flame,
    accent: "pink",
    kind: "single",
    inputPlaceholder: { en: "Video/reel/post topic…", hi: "वीडियो/रील का विषय…" },
    badge: { en: "Hot", hi: "हॉट" },
  },
  {
    id: "yt-title",
    name: { en: "YouTube Title Generator", hi: "YouTube टाइटल जनरेटर" },
    tagline: { en: "Click-worthy SEO titles.", hi: "क्लिक खींचने वाले टाइटल।" },
    category: "creator",
    icon: Youtube,
    accent: "pink",
    kind: "single",
    inputPlaceholder: { en: "Video topic / niche…", hi: "वीडियो का विषय…" },
  },
  {
    id: "reel-script",
    name: { en: "Reel Script Generator", hi: "रील स्क्रिप्ट" },
    tagline: { en: "15–60 sec reel scripts.", hi: "15–60 सेकंड की रील स्क्रिप्ट।" },
    category: "creator",
    icon: Clapperboard,
    accent: "violet",
    kind: "single",
    inputPlaceholder: { en: "Reel topic / hook…", hi: "रील का विषय…" },
  },
  {
    id: "reel-idea",
    name: { en: "Reel / Shorts Idea", hi: "रील / शॉर्ट्स आइडिया" },
    tagline: { en: "Viral short-form ideas.", hi: "वायरल शॉर्ट आइडिया।" },
    category: "creator",
    icon: Film,
    accent: "accent",
    kind: "single",
    inputPlaceholder: { en: "Niche or channel topic…", hi: "चैनल/निच…" },
  },
  {
    id: "content-idea",
    name: { en: "Content Idea Generator", hi: "कंटेंट आइडिया" },
    tagline: { en: "30-day content calendars.", hi: "30-दिन का कंटेंट प्लान।" },
    category: "creator",
    icon: Lightbulb,
    accent: "amber",
    kind: "single",
    inputPlaceholder: { en: "Brand / niche / audience…", hi: "ब्रांड / निच / ऑडियंस…" },
  },
  {
    id: "thumbnail-idea",
    name: { en: "Thumbnail Idea", hi: "थंबनेल आइडिया" },
    tagline: { en: "High-CTR thumbnail concepts.", hi: "High-CTR थंबनेल आइडिया।" },
    category: "creator",
    icon: ImageLucide,
    accent: "primary",
    kind: "single",
    inputPlaceholder: { en: "Video title or topic…", hi: "वीडियो टाइटल / विषय…" },
  },
  {
    id: "storyboard",
    name: { en: "Storyboard Generator", hi: "स्टोरीबोर्ड" },
    tagline: { en: "Scene-by-scene shot plan.", hi: "सीन-दर-सीन शॉट प्लान।" },
    category: "creator",
    icon: Sparkles,
    accent: "violet",
    kind: "single",
    inputPlaceholder: { en: "Story or ad concept…", hi: "कहानी / ऐड का concept…" },
  },
  {
    id: "image-prompt",
    name: { en: "AI Image Prompt", hi: "AI इमेज प्रॉम्प्ट" },
    tagline: { en: "Pro prompts for image AIs.", hi: "इमेज AI के लिए प्रो प्रॉम्प्ट।" },
    category: "media",
    icon: Sparkles,
    accent: "amber",
    kind: "single",
    inputPlaceholder: { en: "What do you want to see?", hi: "क्या बनवाना है?" },
  },
  {
    id: "translate",
    name: { en: "Translation Tool", hi: "अनुवाद उपकरण" },
    tagline: { en: "Hindi ↔ English (and more).", hi: "हिंदी ↔ अंग्रेज़ी।" },
    category: "writing",
    icon: Languages,
    accent: "accent",
    kind: "single",
    inputPlaceholder: { en: "Text to translate…", hi: "अनुवाद हेतु पाठ…" },
  },
  {
    id: "whatsapp",
    name: { en: "WhatsApp Reply", hi: "WhatsApp जवाब" },
    tagline: { en: "Smart replies in your voice.", hi: "स्मार्ट जवाब।" },
    category: "social",
    icon: MessageCircle,
    accent: "accent",
    kind: "single",
    inputLabel: { en: "Paste the message", hi: "संदेश पेस्ट करें" },
    inputPlaceholder: { en: "What did they say?", hi: "उन्होंने क्या लिखा?" },
  },
  {
    id: "image",
    name: { en: "AI Image Generator", hi: "AI चित्र जनरेटर" },
    tagline: { en: "Text-to-image studio powered by Gemini.", hi: "Gemini से टेक्स्ट-से-चित्र।" },
    category: "media",
    icon: ImageIcon,
    accent: "violet",
    kind: "single",
    inputPlaceholder: {
      en: "Describe the image you want, e.g. 'A neon aurora over Himalayan peaks at dusk'.",
      hi: "जो चित्र चाहिए वो लिखें, जैसे 'हिमालय पर सांझ की नीयन अरोरा'।",
    },
    badge: { en: "New", hi: "नया" },
  },
  {
    id: "video",
    name: { en: "AI Video Studio", hi: "AI वीडियो स्टूडियो" },
    tagline: { en: "Reel & Shorts planning suite.", hi: "रील व शॉर्ट्स प्लानिंग।" },
    category: "media",
    icon: Video,
    accent: "pink",
    kind: "placeholder",
    badge: { en: "Coming soon", hi: "जल्द आ रहा है" },
  },
  {
    id: "audio",
    name: { en: "AI Voice & Audio", hi: "AI आवाज़ व ऑडियो" },
    tagline: { en: "Voice cloning & enhancement.", hi: "वॉइस क्लोनिंग व सुधार।" },
    category: "media",
    icon: Mic,
    accent: "amber",
    kind: "placeholder",
    badge: { en: "Coming soon", hi: "जल्द आ रहा है" },
  },
];

export function getTool(id: string) {
  return TOOLS.find((t) => t.id === id);
}

export const ACCENT_CLASSES: Record<Tool["accent"], { bg: string; text: string; ring: string }> = {
  primary: { bg: "bg-primary/10", text: "text-primary", ring: "hover:border-primary/40" },
  accent: { bg: "bg-accent/10", text: "text-accent", ring: "hover:border-accent/40" },
  pink: { bg: "bg-pink-500/10", text: "text-pink-400", ring: "hover:border-pink-500/40" },
  amber: { bg: "bg-amber-400/10", text: "text-amber-400", ring: "hover:border-amber-400/40" },
  violet: { bg: "bg-violet-500/10", text: "text-violet-400", ring: "hover:border-violet-500/40" },
};
